import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding database...");

  // ── Demo user ──────────────────────────────────────────────────────────────
  const user = await prisma.user.upsert({
    where: { email: "demo@example.com" },
    update: {},
    create: {
      email: "demo@example.com",
      name: "Jake Torres",
    },
  });

  // ── Business ──────────────────────────────────────────────────────────────
  const biz = await prisma.business.upsert({
    where: { id: "seed-biz-001" },
    update: {},
    create: {
      id: "seed-biz-001",
      userId: user.id,
      name: "Peak Performance HVAC",
      type: "both",
      industry: "HVAC & Mechanical",
      description: "Residential and commercial HVAC installation, repair, and maintenance.",
      address: "4821 Burnet Rd",
      city: "Austin",
      state: "TX",
      zip: "78756",
      phone: "(512) 555-0190",
      email: "dispatch@peakperformancehvac.com",
      website: "https://peakperformancehvac.com",
      currency: "USD",
      timezone: "America/Chicago",
      taxRate: 8.25,
    },
  });

  // ── Customers ─────────────────────────────────────────────────────────────
  const customers = await Promise.all([
    prisma.customer.upsert({
      where: { id: "seed-cust-001" },
      update: {},
      create: {
        id: "seed-cust-001",
        businessId: biz.id,
        name: "Maria Gonzalez",
        email: "maria.g@email.com",
        phone: "(512) 555-0201",
        address: "1402 Lavaca St",
        city: "Austin",
        state: "TX",
        zip: "78701",
        type: "residential",
        notes: "Prefers morning appointments. Two-story home, two systems.",
      },
    }),
    prisma.customer.upsert({
      where: { id: "seed-cust-002" },
      update: {},
      create: {
        id: "seed-cust-002",
        businessId: biz.id,
        name: "Brendan Walsh",
        company: "Walsh Properties LLC",
        email: "b.walsh@walshproperties.com",
        phone: "(512) 555-0334",
        address: "600 Congress Ave",
        city: "Austin",
        state: "TX",
        zip: "78701",
        type: "business",
        notes: "Commercial property manager. 8 units, annual maintenance contracts.",
      },
    }),
    prisma.customer.upsert({
      where: { id: "seed-cust-003" },
      update: {},
      create: {
        id: "seed-cust-003",
        businessId: biz.id,
        name: "Sandra Kim",
        email: "sandrakim@gmail.com",
        phone: "(512) 555-0412",
        address: "7803 Shoal Creek Blvd",
        city: "Austin",
        state: "TX",
        zip: "78757",
        type: "residential",
        notes: "New customer, referred by Maria Gonzalez.",
      },
    }),
    prisma.customer.upsert({
      where: { id: "seed-cust-004" },
      update: {},
      create: {
        id: "seed-cust-004",
        businessId: biz.id,
        name: "Derek Okafor",
        company: "Okafor Restaurants Group",
        email: "derek@okaforrestaurants.com",
        phone: "(512) 555-0587",
        address: "2501 South Lamar Blvd",
        city: "Austin",
        state: "TX",
        zip: "78704",
        type: "business",
        notes: "Three restaurant locations. High-priority — commercial kitchen cooling is critical.",
      },
    }),
    prisma.customer.upsert({
      where: { id: "seed-cust-005" },
      update: {},
      create: {
        id: "seed-cust-005",
        businessId: biz.id,
        name: "Priya Nair",
        email: "priya.nair@icloud.com",
        phone: "(512) 555-0699",
        address: "3210 Manchaca Rd",
        city: "Austin",
        state: "TX",
        zip: "78704",
        type: "residential",
      },
    }),
    prisma.customer.upsert({
      where: { id: "seed-cust-006" },
      update: {},
      create: {
        id: "seed-cust-006",
        businessId: biz.id,
        name: "Tom Reyes",
        company: "Reyes Auto Group",
        email: "tom@reyesauto.com",
        phone: "(512) 555-0723",
        address: "11200 Research Blvd",
        city: "Austin",
        state: "TX",
        zip: "78759",
        type: "business",
        notes: "New dealership build-out. Large commercial installation, multi-zone.",
      },
    }),
  ]);

  const [maria, brendan, sandra, derek, priya, tom] = customers;

  // ── Products / Inventory ──────────────────────────────────────────────────
  const products = await Promise.all([
    prisma.product.upsert({
      where: { id: "seed-prod-001" },
      update: {},
      create: {
        id: "seed-prod-001",
        businessId: biz.id,
        name: "Lennox XC21 3-Ton AC Unit",
        sku: "LEN-XC21-036",
        description: "High-efficiency split system air conditioner, 21 SEER",
        type: "product",
        unitCost: 1850,
        unitPrice: 2600,
        unit: "each",
        stockLevel: 4,
        minStock: 2,
        category: "AC Units",
        supplier: "Lennox Distributor Austin",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-002" },
      update: {},
      create: {
        id: "seed-prod-002",
        businessId: biz.id,
        name: "Carrier 80% AFUE Furnace",
        sku: "CAR-58CV-080",
        description: "Variable-speed gas furnace, 80,000 BTU",
        type: "product",
        unitCost: 920,
        unitPrice: 1350,
        unit: "each",
        stockLevel: 3,
        minStock: 2,
        category: "Furnaces",
        supplier: "Carrier Wholesale",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-003" },
      update: {},
      create: {
        id: "seed-prod-003",
        businessId: biz.id,
        name: "Ecobee SmartThermostat Premium",
        sku: "ECO-ST-PREM",
        description: "Smart thermostat with built-in Alexa, room sensors included",
        type: "product",
        unitCost: 168,
        unitPrice: 249,
        unit: "each",
        stockLevel: 12,
        minStock: 5,
        category: "Thermostats",
        supplier: "Ecobee Direct",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-004" },
      update: {},
      create: {
        id: "seed-prod-004",
        businessId: biz.id,
        name: "R-410A Refrigerant (25 lb cylinder)",
        sku: "REF-R410A-25",
        description: "R-410A refrigerant, 25 lb disposable cylinder",
        type: "product",
        unitCost: 78,
        unitPrice: 135,
        unit: "cylinder",
        stockLevel: 8,
        minStock: 4,
        category: "Refrigerants",
        supplier: "National Refrigerants Inc.",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-005" },
      update: {},
      create: {
        id: "seed-prod-005",
        businessId: biz.id,
        name: "16x20x1 MERV-13 Air Filter (case of 6)",
        sku: "FIL-1620-M13-6",
        description: "High-efficiency pleated air filters, case of 6",
        type: "product",
        unitCost: 28,
        unitPrice: 48,
        unit: "case",
        stockLevel: 18,
        minStock: 6,
        category: "Filters",
        supplier: "Filterbuy",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-006" },
      update: {},
      create: {
        id: "seed-prod-006",
        businessId: biz.id,
        name: "Flex Duct 8\" x 25 ft",
        sku: "DUCT-FLEX-825",
        description: "R-8 insulated flexible ductwork",
        type: "product",
        unitCost: 42,
        unitPrice: 72,
        unit: "roll",
        stockLevel: 10,
        minStock: 4,
        category: "Ductwork",
        supplier: "Johnstone Supply",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-007" },
      update: {},
      create: {
        id: "seed-prod-007",
        businessId: biz.id,
        name: "Capacitor 45/5 MFD 440V Round",
        sku: "CAP-45-5-440",
        description: "Dual run capacitor for AC compressor and fan motor",
        type: "product",
        unitCost: 8,
        unitPrice: 35,
        unit: "each",
        stockLevel: 20,
        minStock: 10,
        category: "Parts & Components",
        supplier: "Johnstone Supply",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-008" },
      update: {},
      create: {
        id: "seed-prod-008",
        businessId: biz.id,
        name: "Condenser Fan Motor 1/5 HP",
        sku: "MOT-FAN-15HP",
        description: "Universal replacement condenser fan motor",
        type: "product",
        unitCost: 65,
        unitPrice: 145,
        unit: "each",
        stockLevel: 6,
        minStock: 3,
        category: "Parts & Components",
        supplier: "Johnstone Supply",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-009" },
      update: {},
      create: {
        id: "seed-prod-009",
        businessId: biz.id,
        name: "Annual Maintenance Labor (1 system)",
        sku: "SVC-MAINT-1",
        description: "Annual tune-up and maintenance, single system",
        type: "service",
        unitCost: 55,
        unitPrice: 139,
        unit: "each",
        stockLevel: 0,
        minStock: 0,
        category: "Services",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-010" },
      update: {},
      create: {
        id: "seed-prod-010",
        businessId: biz.id,
        name: "HVAC Install Labor (per hour)",
        sku: "SVC-LABOR-HR",
        description: "Technician labor, installation and service calls",
        type: "service",
        unitCost: 0,
        unitPrice: 125,
        unit: "hour",
        stockLevel: 0,
        minStock: 0,
        category: "Services",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-011" },
      update: {},
      create: {
        id: "seed-prod-011",
        businessId: biz.id,
        name: "Lennox SL18XC1 2-Ton AC Unit",
        sku: "LEN-SL18-024",
        description: "18 SEER split-system air conditioner, 2 ton",
        type: "product",
        unitCost: 1320,
        unitPrice: 1950,
        unit: "each",
        stockLevel: 2,
        minStock: 1,
        category: "AC Units",
        supplier: "Lennox Distributor Austin",
      },
    }),
    prisma.product.upsert({
      where: { id: "seed-prod-012" },
      update: {},
      create: {
        id: "seed-prod-012",
        businessId: biz.id,
        name: "Honeywell T6 Pro Programmable Thermostat",
        sku: "HON-T6-PROG",
        description: "7-day programmable thermostat, easy install",
        type: "product",
        unitCost: 42,
        unitPrice: 79,
        unit: "each",
        stockLevel: 7,
        minStock: 3,
        category: "Thermostats",
        supplier: "Johnstone Supply",
      },
    }),
  ]);

  // ── Jobs ──────────────────────────────────────────────────────────────────
  const now = new Date();
  const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000);
  const daysAhead = (n: number) => new Date(now.getTime() + n * 86400000);

  const jobs = await Promise.all([
    // Completed jobs
    prisma.job.upsert({
      where: { id: "seed-job-001" },
      update: {},
      create: {
        id: "seed-job-001",
        businessId: biz.id,
        customerId: maria.id,
        title: "AC Replacement - 2nd Floor Unit",
        jobNumber: "JOB-2025-001",
        status: "completed",
        priority: "normal",
        startDate: daysAgo(32),
        endDate: daysAgo(32),
        location: "1402 Lavaca St, Austin TX",
        laborCost: 375,
        materialCost: 1850,
        billedAmount: 3749,
        notes: "Replaced failed 2003-era unit. Installed Lennox XC21 3-ton. Customer very satisfied.",
        items: {
          create: [
            { description: "Lennox XC21 3-Ton AC Unit", quantity: 1, unitCost: 1850, total: 1850, type: "material" },
            { description: "Installation labor (3 hrs)", quantity: 3, unitCost: 125, total: 375, type: "labor" },
          ],
        },
      },
    }),
    prisma.job.upsert({
      where: { id: "seed-job-002" },
      update: {},
      create: {
        id: "seed-job-002",
        businessId: biz.id,
        customerId: brendan.id,
        title: "Annual Maintenance - Walsh Properties Q1",
        jobNumber: "JOB-2025-002",
        status: "completed",
        priority: "normal",
        startDate: daysAgo(18),
        endDate: daysAgo(17),
        location: "600 Congress Ave, Austin TX",
        laborCost: 440,
        materialCost: 144,
        billedAmount: 1112,
        notes: "8-unit annual maintenance complete. Replaced filters on all units. One capacitor replaced on Unit 4.",
      },
    }),
    prisma.job.upsert({
      where: { id: "seed-job-003" },
      update: {},
      create: {
        id: "seed-job-003",
        businessId: biz.id,
        customerId: derek.id,
        title: "Emergency Repair - South Lamar Kitchen Cooling",
        jobNumber: "JOB-2025-003",
        status: "completed",
        priority: "urgent",
        startDate: daysAgo(10),
        endDate: daysAgo(10),
        location: "2501 South Lamar Blvd, Austin TX",
        laborCost: 250,
        materialCost: 143,
        billedAmount: 628,
        notes: "Capacitor and fan motor failure on walk-in cooler condenser. Same-day emergency response. Back online within 4 hours.",
        items: {
          create: [
            { description: "Condenser Fan Motor 1/5 HP", quantity: 1, unitCost: 65, total: 65, type: "material" },
            { description: "Capacitor 45/5 MFD 440V", quantity: 1, unitCost: 8, total: 8, type: "material" },
            { description: "Emergency labor (2 hrs)", quantity: 2, unitCost: 125, total: 250, type: "labor" },
          ],
        },
      },
    }),
    // In-progress jobs
    prisma.job.upsert({
      where: { id: "seed-job-004" },
      update: {},
      create: {
        id: "seed-job-004",
        businessId: biz.id,
        customerId: tom.id,
        title: "Commercial Install - Reyes Auto Group Multi-Zone",
        jobNumber: "JOB-2025-004",
        status: "in_progress",
        priority: "high",
        startDate: daysAgo(3),
        endDate: daysAhead(4),
        location: "11200 Research Blvd, Austin TX",
        laborCost: 0,
        materialCost: 0,
        billedAmount: 0,
        notes: "6-zone commercial install for new dealership. Day 3 of 7. Ductwork roughed in, equipment delivery tomorrow.",
      },
    }),
    prisma.job.upsert({
      where: { id: "seed-job-005" },
      update: {},
      create: {
        id: "seed-job-005",
        businessId: biz.id,
        customerId: sandra.id,
        title: "Furnace Tune-Up & Filter Replacement",
        jobNumber: "JOB-2025-005",
        status: "in_progress",
        priority: "normal",
        startDate: now,
        endDate: now,
        location: "7803 Shoal Creek Blvd, Austin TX",
        laborCost: 0,
        materialCost: 0,
        billedAmount: 0,
        notes: "Annual maintenance visit. Tech on site now.",
      },
    }),
    // Scheduled jobs
    prisma.job.upsert({
      where: { id: "seed-job-006" },
      update: {},
      create: {
        id: "seed-job-006",
        businessId: biz.id,
        customerId: priya.id,
        title: "AC Tune-Up & Inspection",
        jobNumber: "JOB-2025-006",
        status: "scheduled",
        priority: "normal",
        startDate: daysAhead(2),
        endDate: daysAhead(2),
        location: "3210 Manchaca Rd, Austin TX",
        laborCost: 0,
        materialCost: 0,
        billedAmount: 0,
        notes: "Pre-summer tune-up. Customer requested 8am–10am window.",
      },
    }),
    prisma.job.upsert({
      where: { id: "seed-job-007" },
      update: {},
      create: {
        id: "seed-job-007",
        businessId: biz.id,
        customerId: brendan.id,
        title: "Thermostat Upgrade - Walsh Units 5-8",
        jobNumber: "JOB-2025-007",
        status: "scheduled",
        priority: "normal",
        startDate: daysAhead(5),
        endDate: daysAhead(5),
        location: "600 Congress Ave, Austin TX",
        laborCost: 0,
        materialCost: 0,
        billedAmount: 0,
        notes: "Replace 4x old thermostats with Ecobee smart thermostats per contract renewal.",
      },
    }),
    prisma.job.upsert({
      where: { id: "seed-job-008" },
      update: {},
      create: {
        id: "seed-job-008",
        businessId: biz.id,
        customerId: derek.id,
        title: "Preventive Maintenance - Okafor North Location",
        jobNumber: "JOB-2025-008",
        status: "scheduled",
        priority: "high",
        startDate: daysAhead(9),
        endDate: daysAhead(9),
        location: "4400 North Lamar Blvd, Austin TX",
        laborCost: 0,
        materialCost: 0,
        billedAmount: 0,
        notes: "Quarterly PM visit before summer heat. Two commercial units.",
      },
    }),
  ]);

  const [job1, job2, job3] = jobs;

  // ── Invoices ──────────────────────────────────────────────────────────────
  await Promise.all([
    // Paid invoices
    prisma.invoice.upsert({
      where: { id: "seed-inv-001" },
      update: {},
      create: {
        id: "seed-inv-001",
        businessId: biz.id,
        customerId: maria.id,
        jobId: job1.id,
        number: "INV-2025-001",
        status: "paid",
        issueDate: daysAgo(31),
        dueDate: daysAgo(1),
        paidAt: daysAgo(28),
        subtotal: 3462.44,
        taxRate: 8.25,
        tax: 285.65,
        total: 3748.09,
        notes: "Thank you for your business! Next annual maintenance due March 2026.",
        items: {
          create: [
            { description: "Lennox XC21 3-Ton AC Unit", quantity: 1, unitPrice: 2600, total: 2600 },
            { description: "AC Installation Labor (3 hrs)", quantity: 3, unitPrice: 125, total: 375 },
            { description: "Thermostat upgrade (Ecobee)", quantity: 1, unitPrice: 249, total: 249 },
            { description: "Disposal & haul-away (old unit)", quantity: 1, unitPrice: 95, total: 95 },
            { description: "Refrigerant top-off", quantity: 1, unitPrice: 143.44, total: 143.44 },
          ],
        },
      },
    }),
    prisma.invoice.upsert({
      where: { id: "seed-inv-002" },
      update: {},
      create: {
        id: "seed-inv-002",
        businessId: biz.id,
        customerId: brendan.id,
        jobId: job2.id,
        number: "INV-2025-002",
        status: "paid",
        issueDate: daysAgo(16),
        dueDate: daysAgo(1),
        paidAt: daysAgo(12),
        subtotal: 1027.32,
        taxRate: 8.25,
        tax: 84.75,
        total: 1112.07,
        notes: "Annual maintenance complete — all 8 units serviced.",
        items: {
          create: [
            { description: "Annual Maintenance Labor (8 units x 1 hr)", quantity: 8, unitPrice: 55, total: 440 },
            { description: "MERV-13 Filters (8 units)", quantity: 8, unitPrice: 8, total: 64 },
            { description: "Capacitor replacement (Unit 4)", quantity: 1, unitPrice: 35, total: 35 },
            { description: "Refrigerant check & report", quantity: 1, unitPrice: 75, total: 75 },
            { description: "Service call fee", quantity: 1, unitPrice: 95, total: 95 },
            { description: "Freon top-off (0.5 lb)", quantity: 1, unitPrice: 67.5, total: 67.5 },
            { description: "Trip charge (2 days)", quantity: 2, unitPrice: 75.41, total: 150.82 },
          ],
        },
      },
    }),
    prisma.invoice.upsert({
      where: { id: "seed-inv-003" },
      update: {},
      create: {
        id: "seed-inv-003",
        businessId: biz.id,
        customerId: derek.id,
        jobId: job3.id,
        number: "INV-2025-003",
        status: "paid",
        issueDate: daysAgo(9),
        dueDate: daysAgo(0),
        paidAt: daysAgo(7),
        subtotal: 580.01,
        taxRate: 8.25,
        tax: 47.85,
        total: 627.86,
        notes: "Emergency same-day service. System restored within 4 hours.",
        items: {
          create: [
            { description: "Emergency service call fee", quantity: 1, unitPrice: 175, total: 175 },
            { description: "Condenser Fan Motor 1/5 HP", quantity: 1, unitPrice: 145, total: 145 },
            { description: "Capacitor 45/5 MFD 440V", quantity: 1, unitPrice: 35, total: 35 },
            { description: "Emergency labor (2 hrs)", quantity: 2, unitPrice: 125, total: 250 },
            { description: "Parts & supplies", quantity: 1, unitPrice: 50, total: 50 },
          ],
        },
      },
    }),
    // Sent / awaiting payment
    prisma.invoice.upsert({
      where: { id: "seed-inv-004" },
      update: {},
      create: {
        id: "seed-inv-004",
        businessId: biz.id,
        customerId: brendan.id,
        number: "INV-2025-004",
        status: "sent",
        issueDate: daysAgo(5),
        dueDate: daysAhead(25),
        subtotal: 1152.41,
        taxRate: 8.25,
        tax: 95.07,
        total: 1247.48,
        notes: "Thermostat upgrade + Q2 filter subscription — 4 units.",
        items: {
          create: [
            { description: "Ecobee SmartThermostat Premium (x4)", quantity: 4, unitPrice: 249, total: 996 },
            { description: "Installation labor (4 hrs)", quantity: 4, unitPrice: 38.60, total: 154.41 },
            { description: "Programming & setup", quantity: 1, unitPrice: 75, total: 75 },
          ],
        },
      },
    }),
    prisma.invoice.upsert({
      where: { id: "seed-inv-005" },
      update: {},
      create: {
        id: "seed-inv-005",
        businessId: biz.id,
        customerId: priya.id,
        number: "INV-2025-005",
        status: "sent",
        issueDate: daysAgo(2),
        dueDate: daysAhead(28),
        subtotal: 185.05,
        taxRate: 8.25,
        tax: 15.27,
        total: 200.32,
        notes: "Spring tune-up complete. System is in good shape.",
        items: {
          create: [
            { description: "Annual Maintenance - 1 System", quantity: 1, unitPrice: 139, total: 139 },
            { description: "MERV-13 Filter replacement", quantity: 1, unitPrice: 48, total: 48 },
            { description: "Coil cleaning (light)", quantity: 1, unitPrice: 65, total: 65 },
          ],
        },
      },
    }),
    // Overdue invoices
    prisma.invoice.upsert({
      where: { id: "seed-inv-006" },
      update: {},
      create: {
        id: "seed-inv-006",
        businessId: biz.id,
        customerId: derek.id,
        number: "INV-2025-006",
        status: "overdue",
        issueDate: daysAgo(45),
        dueDate: daysAgo(15),
        subtotal: 2890.00,
        taxRate: 8.25,
        tax: 238.43,
        total: 3128.43,
        notes: "Q4 preventive maintenance — 3 locations. Payment overdue. Follow up required.",
        items: {
          create: [
            { description: "Commercial PM Service (3 locations)", quantity: 3, unitPrice: 650, total: 1950 },
            { description: "Filter replacements (commercial)", quantity: 6, unitPrice: 48, total: 288 },
            { description: "Refrigerant top-off (2 systems)", quantity: 2, unitPrice: 135, total: 270 },
            { description: "Condenser coil cleaning", quantity: 3, unitPrice: 127.33, total: 382 },
          ],
        },
      },
    }),
    // Draft
    prisma.invoice.upsert({
      where: { id: "seed-inv-007" },
      update: {},
      create: {
        id: "seed-inv-007",
        businessId: biz.id,
        customerId: tom.id,
        number: "INV-2025-007",
        status: "draft",
        issueDate: now,
        dueDate: daysAhead(30),
        subtotal: 0,
        taxRate: 8.25,
        tax: 0,
        total: 0,
        notes: "Commercial installation deposit — Reyes Auto Group. Final invoice pending job completion.",
      },
    }),
  ]);

  // ── Leads ──────────────────────────────────────────────────────────────────
  await Promise.all([
    prisma.lead.upsert({
      where: { id: "seed-lead-001" },
      update: {},
      create: {
        id: "seed-lead-001",
        businessId: biz.id,
        customerId: tom.id,
        title: "Reyes Auto Group - Multi-Zone Commercial Install",
        stage: "won",
        value: 28500,
        source: "referral",
        probability: 100,
        closedAt: daysAgo(14),
        notes: "Largest single contract this year. Referral from Okafor. Installation in progress.",
      },
    }),
    prisma.lead.upsert({
      where: { id: "seed-lead-002" },
      update: {},
      create: {
        id: "seed-lead-002",
        businessId: biz.id,
        title: "Riverside Medical - 12 Exam Room Splits",
        stage: "proposal",
        value: 42000,
        source: "website",
        probability: 60,
        followUpAt: daysAhead(3),
        notes: "Medical office renovation. Sent quote for 12 mini-splits. Decision by end of month.",
      },
    }),
    prisma.lead.upsert({
      where: { id: "seed-lead-003" },
      update: {},
      create: {
        id: "seed-lead-003",
        businessId: biz.id,
        customerId: sandra.id,
        title: "Sandra Kim - Full System Replacement",
        stage: "negotiation",
        value: 8200,
        source: "referral",
        probability: 75,
        followUpAt: daysAhead(1),
        notes: "Referred by Maria Gonzalez. Wants full AC + furnace replacement before summer. Price-sensitive.",
      },
    }),
    prisma.lead.upsert({
      where: { id: "seed-lead-004" },
      update: {},
      create: {
        id: "seed-lead-004",
        businessId: biz.id,
        title: "Mueller Neighborhood New Construction - 22 Units",
        stage: "contacted",
        value: 85000,
        source: "cold-outreach",
        probability: 25,
        followUpAt: daysAhead(7),
        notes: "New residential development. Builder is comparing 3 HVAC contractors. Very large opportunity.",
      },
    }),
    prisma.lead.upsert({
      where: { id: "seed-lead-005" },
      update: {},
      create: {
        id: "seed-lead-005",
        businessId: biz.id,
        title: "Austin Community Church - Sanctuary System",
        stage: "new",
        value: 15000,
        source: "google",
        probability: 30,
        followUpAt: daysAhead(2),
        notes: "Inbound inquiry from website. Large sanctuary, likely needs custom zoning solution.",
      },
    }),
    prisma.lead.upsert({
      where: { id: "seed-lead-006" },
      update: {},
      create: {
        id: "seed-lead-006",
        businessId: biz.id,
        title: "SoCo Boutique Hotel - Lobby & Hallway Zones",
        stage: "new",
        value: 19500,
        source: "yelp",
        probability: 20,
        notes: "New lead via Yelp. Hotel reopening after renovation. Needs site assessment first.",
      },
    }),
  ]);

  // ── Expenses ──────────────────────────────────────────────────────────────
  await Promise.all([
    prisma.expense.upsert({
      where: { id: "seed-exp-001" },
      update: {},
      create: {
        id: "seed-exp-001",
        businessId: biz.id,
        description: "Lennox equipment order - spring stock",
        amount: 9250,
        category: "materials",
        date: daysAgo(28),
        vendor: "Lennox Distributor Austin",
        notes: "5x AC units for spring season inventory.",
      },
    }),
    prisma.expense.upsert({
      where: { id: "seed-exp-002" },
      update: {},
      create: {
        id: "seed-exp-002",
        businessId: biz.id,
        description: "R-410A refrigerant restock (10 cylinders)",
        amount: 780,
        category: "materials",
        date: daysAgo(21),
        vendor: "National Refrigerants Inc.",
      },
    }),
    prisma.expense.upsert({
      where: { id: "seed-exp-003" },
      update: {},
      create: {
        id: "seed-exp-003",
        businessId: biz.id,
        description: "Van fuel & maintenance - March",
        amount: 618.40,
        category: "vehicle",
        date: daysAgo(14),
        vendor: "Various",
      },
    }),
    prisma.expense.upsert({
      where: { id: "seed-exp-004" },
      update: {},
      create: {
        id: "seed-exp-004",
        businessId: biz.id,
        description: "EPA 608 certification renewal - 2 techs",
        amount: 120,
        category: "training",
        date: daysAgo(30),
        vendor: "ESCO Institute",
      },
    }),
    prisma.expense.upsert({
      where: { id: "seed-exp-005" },
      update: {},
      create: {
        id: "seed-exp-005",
        businessId: biz.id,
        description: "Johnstone Supply - parts & misc",
        amount: 442.85,
        category: "materials",
        date: daysAgo(7),
        vendor: "Johnstone Supply",
        notes: "Capacitors, contactors, and wire - weekly stock run.",
      },
    }),
    prisma.expense.upsert({
      where: { id: "seed-exp-006" },
      update: {},
      create: {
        id: "seed-exp-006",
        businessId: biz.id,
        description: "Liability insurance premium - Q1",
        amount: 1850,
        category: "insurance",
        date: daysAgo(35),
        vendor: "Texas Mutual",
      },
    }),
    prisma.expense.upsert({
      where: { id: "seed-exp-007" },
      update: {},
      create: {
        id: "seed-exp-007",
        businessId: biz.id,
        description: "Google Ads - HVAC repair Austin",
        amount: 350,
        category: "marketing",
        date: daysAgo(15),
        vendor: "Google",
        notes: "Monthly PPC budget for repair + install keywords.",
      },
    }),
    prisma.expense.upsert({
      where: { id: "seed-exp-008" },
      update: {},
      create: {
        id: "seed-exp-008",
        businessId: biz.id,
        description: "Office rent - March",
        amount: 975,
        category: "rent",
        date: daysAgo(22),
        vendor: "Burnet Rd Properties",
      },
    }),
  ]);

  console.log(`Done! Seeded:`);
  console.log(`  1 user (demo@example.com)`);
  console.log(`  1 business (Peak Performance HVAC)`);
  console.log(`  6 customers`);
  console.log(`  12 products`);
  console.log(`  8 jobs`);
  console.log(`  7 invoices`);
  console.log(`  6 leads`);
  console.log(`  8 expenses`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
